version: "3"

services:
  sonarqube:
    image: sonarqube:8.5.1-community
    container_name: sonarqube
    depends_on:
      - db
    environment:
      SONAR_SEARCH_JAVAADDITIONALOPTS: -Dbootstrap.system_call_filter=false
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ${INSTALL_DIR}/data:/opt/sonarqube/data
      - ${INSTALL_DIR}/extensions:/opt/sonarqube/extensions
      - ${INSTALL_DIR}/logs:/opt/sonarqube/logs
      - ${INSTALL_DIR}/temp:/opt/sonarqube/temp
    ports:
      - "2974:9000"
  db:
    image: postgres:12
    container_name: sonarqube-postgres
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - ${INSTALL_DIR}/postgres:/var/lib/postgresql
      - ${INSTALL_DIR}/postgres_data:/var/lib/postgresql/data